name: ogurets_flutter
description: Ogurets Support for Flutter.
version: 1.1.2
authors:
  - Irina Southwell <pishisuda11@gmail.com>
  - Richard Vowles <richard@bluetrainsoftware.com>
homepage: https://github.com/dart-ogurets/OguretsFlutter
environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  ogurets: ^3.1.1
  flutter_driver:
    sdk: flutter
  logging: ^0.11.3+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

